namespace CardGame.Console
{
    /// <summary>
    ///     Dummy class used to simplify saving/loading bindings where the service is bound to a proxy factory generated by Ninject.
    /// </summary>
    private class FactoryType { }
}